spring:
  application:
    name: register-app

server:
  port: 8761

logging:
  level:
    com.netflix.eureka: false
    com.netflix.discovery: false

eureka:
  instance:
    hostname: register-app
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://register-app:8761/eureka