spring:
  application:
    name: documentation-app

server:
  port: 9093

logging:
  level:
    com.netflix.eureka: true
    com.netflix.discovery: true

eureka:
  instance:
    appname: documentation-app
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://register-app:8761/eureka/

swagger:
  config:
    refreshrate: 10000
  default:
    url: /v2/api-docs