project:
   version: ^project.version^
   title: Person REST CRUD operations API in Spring-Boot 2
   description: Sample REST API for centalized documentation using Spring Boot and spring-fox swagger 2
   termsServiceUrl: 
   contact:
     name: Satish Sharma
     url: https://github.com/hellosatish
     email: https://github.com/hellosatish

spring:
  application:
    name: ^project.artifactId^
  datasource:
    url: jdbc:h2:mem:person-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      path: /db-console

server:
  port: 9091
  servlet:
     context-path: /v1

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

eureka:
  instance:
    appname: ^project.artifactId^
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://register-app:8761/eureka/
